# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindOfCoffeeApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 5.0'
  pod 'JGProgressHUD'

  # Pods for FindOfCoffeeApp

end
